
export type REGISTER_REQUEST = 'USERS_REGISTER_REQUEST'
export type REGISTER_SUCCESS = 'USERS_REGISTER_SUCCESS'
export type REGISTER_FAILURE = 'USERS_REGISTER_FAILURE'

export type LOGIN_REQUEST = 'USERS_LOGIN_REQUEST'
export type LOGIN_SUCCESS = 'USERS_LOGIN_SUCCESS'
export type LOGIN_FAILURE = 'USERS_LOGIN_FAILURE'

export type LOGOUT = 'USERS_LOGOUT'


